name: Show Push Info

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  display-info:
    runs-on: ubuntu-latest
    steps:
      - name: Mostra a data e hora
        run: echo "O push foi feito em $(date)"

      - name: Mostra o usuário
        run: echo "Push feito por ${{ github.actor }}"
